#KissMod Configuration
#Tue Jul 28 02:54:09 KRAT 2026
centerOffsetX=0.0
centerOffsetY=0.0
centerOffsetZ=0.0
debugLogging=false
maxOffsetX=0.5
maxOffsetY=0.5
maxOffsetZ=0.5
particleCount=10
proxLibEnabled=false
proxLibServerList=
proxLibWhitelistMode=false
rightClickEnabled=false
showOthersKiss=true
showOwnKiss=true
soundEnabled=true
soundPitch=1.0
soundVolume=1.0
triggerCooldown=175
